import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistMono.variable,
        inter.variable,
        "font-sans",
        "dark"
      )}
    >
      <body
        className={cn(
          "min-h-full flex flex-col items-center justify-center gap-16 font-sans",
          "bg-black text-zinc-100 py-16 px-8"
        )}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
