CREATE TABLE IF NOT EXISTS "posts" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"content" TEXT NOT NULL,
	"tags" TEXT ARRAY,
	"author" VARCHAR(255) NOT NULL DEFAULT 'David Václavík',
	"published" BOOLEAN NOT NULL DEFAULT FALSE,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

-- Added content_json column to store structured content for future use with rich text editor, later we will remove the content column and use content_json exclusively
ALTER TABLE "posts"
ADD COLUMN IF NOT EXISTS "content_json" JSONB;
-- TODO: change content to description and content_json to content


CREATE TABLE IF NOT EXISTS "comments" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"content" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP,
	"post_id" INTEGER NOT NULL,
	"user_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE INDEX "idx_comments_post_id"
ON "comments" ("post_id");


CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password_hash" VARCHAR(255) NOT NULL,
	"is_admin" BOOLEAN NOT NULL DEFAULT false,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

ALTER TABLE "comments"
ADD FOREIGN KEY("post_id") REFERENCES "posts"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "comments"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

-- TODO: convert all TIMESTAMP to TIMESTAMPTZ, so we have timezone support, and we can display dates in user's local timezone on frontend